export { EmployeeHero } from './EmployeeHero';
export { EmployeeSidebar } from './EmployeeSidebar';
export { OverviewTab } from './OverviewTab';
export { HistoryTab } from './HistoryTab';
export { DocumentsTab } from './DocumentsTab';
export { TrainingTab } from './TrainingTab';
export { PerformanceTab } from './PerformanceTab';
export { EmployeeModals } from './EmployeeModals';
export { LeaveQuotaTab } from './LeaveQuotaTab';
export type * from './EmployeeDetailTypes';
